@startuml "Consumption State Diagram"
title Consumption State Diagram
hide empty description
left to right direction

[*] --> PRISTINE
PRISTINE --> IN_PROGRESS
IN_PROGRESS --> COMPLETED
COMPLETED --> [*]
@enduml
