@startuml "Transaction Flow"
title "Transaction Flow"

collections Banks
actor Member
actor Author
boundary Frontend as FE
control Backend as BE
database Database as DB

autonumber
autoactivate on

Member -> FE: Purchase Course
return Instructions
Member -> Banks: Pay
return Receipt
Member -> FE: Confirm Payment
return WhatsApp Link
Member -> Author: Contact WhatsApp
return Reply

autoactivate off
Member -> Author: Upload Receipt
autoactivate on

Author -> FE: View Transaction Details
FE -> BE: Loader
BE -> DB: Query
return Data
return Data
return Transaction Details

Author -> Banks: Verify Payment

autoactivate off

alt Not Confirmed
  Banks --> Author: Payment Not Received
  autoactivate on
  Author -> Member: Contact WhatsApp
  return Reply
else Confirmed
  return Payment Received
  Author -> FE: Verify Purchase
  FE -> BE: Action
  BE -> DB: Mutation
  return Data

  autoactivate off
  BE -> Member: Notify via Email
  autoactivate on

  return Data
  return Purchase Verified
end

Member -> FE: Consume Course
return Course Content
@enduml
