@startuml "Transaction Flow"
title "Transaction Flow"

collections Banks
actor Member
actor Author
boundary Frontend as FE
control Backend as BE
database Database as DB

autonumber
autoactivate on

Member -> FE: Purchase Course
return Instructions
Member -> Banks: Pay
return Receipt
Member -> FE: Confirm Payment
return WhatsApp Link
Member -> Author: Contact WhatsApp
return Reply

autoactivate off
Member -> Author: Upload Receipt
autoactivate on

Author -> FE: View Member Detail
FE -> BE: Load Member Detail
BE -> DB: Query
return Response
return Member Detail
return Member Detail

Author -> Banks: Verify Payment

autoactivate off

alt Not Confirmed
  Banks --> Author: Payment Not Received
  autoactivate on
  Author -> Member: Contact WhatsApp
  return Reply
else Confirmed
  return Payment Received
  Author -> FE: Verify Purchase
  FE -> BE: Action Verify Purchase
  BE -> DB: Mutation
  return Response

  autoactivate off
  BE -> Member: Notify Email
  autoactivate on

  return Purchase Verified
  return Purchase Verified
end

Member -> FE: Consume Course
return Course Content
@enduml
