@startuml "Use Cases"
title Use Cases
left to right direction

actor User as user
actor Author as author
actor Admin as admin

usecase Authenticate as auth

package Course {
  usecase "Create Course" as create
  usecase "Consume Course" as consume
  package Transaction {
    usecase "Purchase Course" as purchase
    usecase "Confirm Purchase" as confirm
    usecase "Grant Course" as grant
  }
}

user <|-- author
author <|-- admin
consume <|-- create
purchase <|-- confirm
confirm <|-- grant

user -left-> auth
author --> create
user --> purchase
author --> confirm
admin --> grant
user --> consume
@enduml
