@startuml "Use Cases"
title Use Cases

actor Visitor

package User {
  actor Member
  actor Author
  actor Admin
}

usecase "View Course" as view
usecase Authenticate as auth

package Course {
  usecase "Create Course" as create
  package Subscription {
    usecase "Consume Course" as consume
    usecase "Grant Course" as grant
  }
  package Transaction {
    usecase "Purchase Course" as purchase
    usecase "Confirm Purchase" as confirm
  }
}

Visitor <|-- Member
Member <|-- Author
Author <|-- Admin
consume <|-- grant
grant <|-- create
purchase <|-- confirm

Visitor -left-> view
Member -left-> auth
Author -right-> create
Member --> purchase
Author --> confirm
Author --> grant
Member --> consume
@enduml
