export const ROLES = {
  ADMIN: 'ADMIN',
  AUTHOR: 'AUTHOR',
  MEMBER: 'MEMBER',
}

export const SUBSCRIPTION_STATUS = {
  INACTIVE: 'INACTIVE',
  ACTIVE: 'ACTIVE',
}

export const TRANSACTION_STATUS = {
  SUBMITTED: 'SUBMITTED',
  VERIFIED: 'VERIFIED',
}
